version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: ujson
    versions:
    - 4.0.1
  - dependency-name: cornice
    versions:
    - 5.0.3
  - dependency-name: pyjwt
    versions:
    - 2.0.0
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: idna
    versions:
    - "3.0"
  - dependency-name: cffi
    versions:
    - 1.14.4
  - dependency-name: urllib3
    versions:
    - 1.26.2
  - dependency-name: kinto
    versions:
    - 14.1.3
  - dependency-name: iso8601
    versions:
    - 0.1.13
