language: python
dist: bionic
services: redis-server
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install tox
  - pip install -q tox-travis
script:
  - tox
install:
    - pip install tox tox-travis
script:
    - tox
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
